export enum AppActionType {
  SET_FIRST_DOWNLOAD = 'SET_FIRST_DOWNLOAD',
  SET_LOADED = 'SET_LOADED',
  SET_THEME = 'SET_THEME',
  SET_DRAWER_REF = 'SET_DRAWER_REF',
  SET_DRAWER_LOCK_MODE = 'SET_DRAWER_LOCK_MODE',
  SET_BOT_NAV_VIS = 'SET_BOT_NAV_VIS',
  SET_INTERNET_ACCESS = 'SET_INTERNET_ACCESS',
}
