export enum AppActionType {
  SET_FIRST_DOWNLOAD = 'SET_FIRST_DOWNLOAD',
  SET_LOADED = 'SET_LOADED',
  SET_THEME = 'SET_THEME',
  SET_DRAWER_REF = 'SET_DRAWER_REF',
  SET_DRAWER_LOCK_MODE = 'SET_DRAWER_LOCK_MODE',
}
